### ISSUE TITLE
pydruid installation failinf 

### ISSUE THREAD

**Issue by sangmeshcp** [druid-io/pydruid#129]

**Comment by mistercrunch** [comment]
Weird. Can you `pip install pytest-runner` ? I tried to recreate from scratch in both py2.7 and py3.6 and it just worked...

**Comment by msestak** [comment]
Similar issue:

[root@tardis python36]# /root/pydev/py36-venv/bin/pip download --proxy=http://proxyuser:proxypass@proxy:8080 pydruid --dest=/tmp/python36
Collecting pydruid
  File was already downloaded /tmp/python36/pydruid-0.5.0.tar.gz
Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [Errno 101] Network is unreachable -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-e3u9k_pm/pydruid/setup.py", line 44, in <module>
        include_package_data=True,
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

Download of pytest-runner works:
[root@tardis python36]# /root/pydev/py36-venv/bin/pip download --proxy=http://proxyuser:proxypass@proxy:8080 pytest-runner --dest=/tmp/python36
Collecting pytest-runner
  File was already downloaded /tmp/python36/pytest_runner-4.2-py2.py3-none-any.whl
Successfully downloaded pytest-runner

setup.py:
`import sys
from setuptools import setup

install_requires = [
    "six >= 1.9.0",
    "requests",
]

extras_require = {
    "pandas": ["pandas"],
    "async": ["tornado"],
    "sqlalchemy": ["sqlalchemy"],
    "cli": ["pygments", "prompt_toolkit<2.0.0", "tabulate"],
}

# only require simplejson on python < 2.6
if sys.version_info < (2, 6):
    install_requires.append("simplejson >= 3.3.0")

setup(
    name='pydruid',
    version='0.5.0',
    author='Druid Developers',
    author_email='druid-development@googlegroups.com',
    packages=['pydruid', 'pydruid.db', 'pydruid.utils'],
    url='https://pypi.python.org/pypi/pydruid/',
    license='Apache License, Version 2.0',
    description='A Python connector for Druid.',
    long_description='See https://github.com/druid-io/pydruid for more information.',
    install_requires=install_requires,
    extras_require=extras_require,
    setup_requires=['pytest-runner'],
    tests_require=['pytest', 'six', 'mock'],
    entry_points={
        'console_scripts': [
            'pydruid = pydruid.console:main',
        ],
        'sqlalchemy.dialects': [
            'druid = pydruid.db.sqlalchemy:DruidHTTPDialect',
            'druid.http = pydruid.db.sqlalchemy:DruidHTTPDialect',
            'druid.https = pydruid.db.sqlalchemy:DruidHTTPSDialect',
        ],
    },
    include_package_data=True,
)
`

**Comment by msestak** [comment]
I checked all versions on PyPi and issue appears from version 0.4.0 - 0.5.0. Versions 0.2.x and 0.3.x download fine (they don't ask for pytest-runner).

**Comment by msestak** [comment]
Problem occurred because this was clean install. Solution was to install pytest-runner before I tried pydruid install.

**Comment by Diliz** [comment]
This bug still exists, why not adding pytest-runner to the dependencies if it's needed by the lib?
