### ISSUE TITLE
Can't load plugin sqlalchemy.dialects:druid

### ISSUE THREAD

**Issue by jmcorreia** [druid-io/pydruid#134]
Hello all!
I'm trying to create a datasource in superset, using pydruid. I can use pydruid cli successfully, but when I try to create a superset datasource, pointing to druid I'm getting this error: "Can't load plugin sqlalchemy.dialects:druid".

Any idea how to solve this?

Best regards.

Superset version
0.15.0 integrated with hadoop

Expected results
Integrate Druid with SQL lab

Actual results
Unable to integrate Druid with SQL lab

Steps to reproduce
Install pydruid and try to create a database using this plugin

**Comment by kuixiang** [comment]
I've met the same error "cannot import name AbortAction" when i execute the command "pydruid http://localhost:8082/druid/v2/sql/",the Trace is:
Traceback (most recent call last):
  File "/home/fee/runtime/anaconda2/envs/mars/bin/pydruid", line 11, in <module>
    load_entry_point('pydruid==0.3.1', 'console_scripts', 'pydruid')()
  File "/home/fee/runtime/anaconda2/envs/mars/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fee/runtime/anaconda2/envs/mars/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/fee/runtime/anaconda2/envs/mars/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/fee/runtime/anaconda2/envs/mars/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pydruid/console.py", line 7, in <module>
ImportError: cannot import name AbortAction

**Comment by mistercrunch** [comment]
CLI is optional, run `pip install pydruid[cli]`. We may want to print/raise a better exception to make that clear. @betodealmeida
