### ISSUE TITLE
a problem with Python 3

### ISSUE THREAD

**Issue by tongwoojun** [druid-io/pydruid#252]
I'm having a problem with Python 3

`Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydruid/client.py", line 550, in _post
    req = urllib.request.Request(url, querystr, headers)
AttributeError: module 'urllib' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a7/Company/monitor/AI-alarm/data/druid.py", line 25, in <module>
    ts = query.groupby(
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydruid/client.py", line 301, in groupby
    return self._post(query)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydruid/client.py", line 554, in _post
    except urllib.error.HTTPError as e:
AttributeError: module 'urllib' has no attribute 'error'
`

in the client.py add "import urllib.request" the Issue fixed

**Comment by Varad2305** [comment]
I'm facing the same error
