### ISSUE TITLE
PyDruid Installation Error??

### ISSUE THREAD

**Issue by philos22** [druid-io/pydruid#81]
this comes up after running pip install pydruid:

  Running setup.py egg_info for package pydruid
    Traceback (most recent call last):
      File "<string>", line 14, in ?
      File "/home/ctsai/build/pydruid/setup.py", line 30, in ?
        tests_require=['pytest', 'six', 'mock'],
      File "/usr/lib64/python2.4/distutils/core.py", line 110, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 219, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 242, in fetch_build_eggs
        for dist in working_set.resolve(
      File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 481, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 717, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 729, in obtain
        return installer(requirement)
      File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 286, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 446, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 471, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 655, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 930, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 919, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 26, in run_setup
        DirectorySandbox(setup_dir).run(
      File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 63, in run
        return func()
      File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 29, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 9
        with io.open('README.rst', encoding='utf-8') as readme:
              ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in ?

  File "/home/ctsai/build/pydruid/setup.py", line 30, in ?

    tests_require=['pytest', 'six', 'mock'],

  File "/usr/lib64/python2.4/distutils/core.py", line 110, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 219, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 242, in fetch_build_eggs

    for dist in working_set.resolve(

  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 481, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 717, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 729, in obtain

    return installer(requirement)

  File "/usr/lib/python2.4/site-packages/setuptools/dist.py", line 286, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 446, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 471, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 655, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 930, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 919, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 26, in run_setup

    DirectorySandbox(setup_dir).run(

  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 63, in run

    return func()

  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 29, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 9

    with io.open('README.rst', encoding='utf-8') as readme:

          ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1

**Comment by dakra** [comment]
The python `with` syntax was introduced with python 2.5, but I guess for pydruid to run you need at least python 2.6.
